FROM golang:1.20-alpine

WORKDIR /app

RUN apk add --update \
    curl \
    && rm -rf /var/cache/apk/*

RUN curl -sSf https://atlasgo.sh | sh

RUN go install github.com/cosmtrek/air@v1.42.0 && \
    go install github.com/roerohan/wait-for-it@v0.2.13

COPY go.mod go.sum ./
RUN go mod download

COPY ./prestart.dev.sh .
RUN chmod +X ./prestart.dev.sh

CMD ["air", "-c", ".air.toml", "serve"]
