server:
  AppVersion: 1.0.0
  Port: 5000
  Mode: Development
  ProcessTimeout: 60
  ReadTimeout: 5
  WriteTimeout: 5
  MigrateOnStart: true

jwt:
  SecretKey: 9056b94a8611363c2c43aa3760d65a48c834744b877b5041fa99a919d5aaf635
  Issuer: go-boilerplate
  AccessTokenExpireDuration: 15
  AccessTokenPrivateKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUNnc2RDdU92MGJDY1FCbjJxOWhIa1U5MWhscFMxWVJNRnBib1VROEI3VkxjVU9LMGMxCmc3TGdNYzh0d2VwQzcvNisweWFkZzIxN1NlNWw2M2RoK0xzZVgwUEQ0ckhtUm1HaW8rbks3ei9wZW9MMUY1a1AKbVc5UU9vQ1NUU3hrTE51RUFYUSt3NmtuMXJiSlpFMlprU1pwLzBRZ2pOckFWTm9OQ2ttVjdHZGdNd0lEQVFBQgpBb0dBUlZPeGhobG83T3RQcHF1U0wyVWhuOHYrVlF2bi9qYmJncEx0MFpybWttNEduOUJJRG14ZEZhQW5rOFFmClB2V3ZYOEJVM291L0JmdWxZRTh2MkJLcEZ3UEpaeTFETWNpY3R2ZDlhUVo0ekI1bFZ4Wk85UWFONVpnSCtWbDAKQjVTNE9mWEtZZFFnTDBiUU1NMmlDclpMVTJaVEJ4YlNDMlUrRkNYVG5LUk45eUVDUVFEK3pYcWI4UXpIemUzYwpHWCt6TkVNOVp6NE9SUG5tK0FyY1hHQksxTkJMWkxJZkVvMG5xUlFBVUMzYit3QjhZOFdqYi9EZWNIUnpleFJYClNvZEVxaWQ3QWtFQW9YTWdhdVVBdUI4T0VsenJmdlZEREM4WWhJblJtRytFNlVFL084bTB5NUtjT29mZXRvd1oKRDlQbFdDb2FyajlwbE9jclZpNG45YU9nV1VDeVJERHdxUUpBTHBuQi9OYy9NU08yaHZTYTZGbDhtclJSSXliMgpWWW16NHMxNlJ2VlpDeERsaXMxSHg2TWlwMVFDcnlMZTJlRWRlbUMwdXRueVVsU0dTZGkxbUpkT0ZRSkFjZ2V1ClRkR1F3SHF1cGFtYmF3QXZhdHVZcFlQeDFZaHVoNURkNkl4K2RZb0hiZytvN2FYbHpaZ0wxRWxvcnNsNitRQ04KUzBFdVdBQkpzTUJSS0hpb2dRSkJBTGhvTUVTZG40UHgrWjE2VWw3Q3B4RTdudjR6anYyTVlRazhzUXRySjl6WgpjVmdCVHJ5YTFsdzhkampmL0pUbS9ZQ2pCOGFYWis4SGdRajlHbVloZmNJPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
  AccessTokenPublicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDZ3NkQ3VPdjBiQ2NRQm4ycTloSGtVOTFobApwUzFZUk1GcGJvVVE4QjdWTGNVT0swYzFnN0xnTWM4dHdlcEM3LzYrMHlhZGcyMTdTZTVsNjNkaCtMc2VYMFBECjRySG1SbUdpbytuSzd6L3Blb0wxRjVrUG1XOVFPb0NTVFN4a0xOdUVBWFErdzZrbjFyYkpaRTJaa1NacC8wUWcKak5yQVZOb05Da21WN0dkZ013SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
  RefreshTokenExpireDuration: 1440
  RefreshTokenPrivateKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUNleFpvelpTa0Q1ZFgwY084ZDlyZ3dpNDdFMGhpekVaTDFOWFVkOWpjRkRXK0FnOTlzCjVhRk1PMWxwSVlhZXFkOXBZQzloNHlnMUNYNVhqT1BORjNDLzZNem5STWJNZlNtMW96ZTBwMUREd0FtNzF1dUsKVzExaFdVZDFOMkZ0M3czMjZoWEZuZDhUaFM5NkxreTFrM0R2bHRmY3JlYjdHTVdRNWwyRzdITFN6d0lEQVFBQgpBb0dBTTkrVHRkOERPNGJJRklraFZzVFpBT05YemU1bXEzcStiT2IrVUwrMDBpM0ZsRk9CbCs2ZWVHMmJsTUdqClhndGFOdTk2QzUxUDhhUWNaelpjNXhFVmdOZlR3MU0yOEN1ZGQ2UkNiUFpVOW9TUjM3ZlFsN1lVNFNwWmQ5RzAKbER6VExWMlZVSGxpUWhYOUx4dHQxZ3d0U2JKUUxaNGdLNTFEQzZjLzlFRmpkc0VDUVFEemRoRjV1ZWZFRnBiLwpjQk5oUzlkeTVxbEI0Y1NWY0s3UW5ZU0RlRzd1NW5BNS92RnVOKzU2WjN4TktFYXFZUFRBeUp6OGdjak5xeDVCCjdFb0tMNzFYQWtFQXB2THhFSnRSMDNRcHFwZ0g1TjNMQzZsbjRSODBCY01aamlITzVyM3ViQktOblBtNk84UjMKaVBMZ1hXeTVsajFqMEZpY2NYdEZLcVdteWw4RjN0NnpTUUpBRXJGMkZncVlLUTR5K2RuNUl2ZFh5NUs2WER5aApnM2ZyZEVrajY1UkxzRHd4VWNLcGR2VUVjcEdQa2IwTjcvY1IwOXVUY2kvazR5WElaUGRubC9DaWNRSkFGbXJJCnM5SW5TcDF1ZXRtdk5hd1NkNTVudEhMY0tXbnBKSXlsbTVZbFRaMndKa1BpSGVSanFKLzBRSmM0MUZPcDgyL3kKa2NwYm56NWZCdzE3WEZITEFRSkJBT0laYlN1aWFWa2tJZGNUM29KVzlpdTZZdUVic1kyZHVwRjVhenNhNGhuYwptaWJIcVNYdW5VaHZ3L2ZOWDZmVktuaHZJR0pFcHFaUFczTnhvbktjYzhFPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
  RefreshTokenPublicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDZXhab3paU2tENWRYMGNPOGQ5cmd3aTQ3RQowaGl6RVpMMU5YVWQ5amNGRFcrQWc5OXM1YUZNTzFscElZYWVxZDlwWUM5aDR5ZzFDWDVYak9QTkYzQy82TXpuClJNYk1mU20xb3plMHAxRER3QW03MXV1S1cxMWhXVWQxTjJGdDN3MzI2aFhGbmQ4VGhTOTZMa3kxazNEdmx0ZmMKcmViN0dNV1E1bDJHN0hMU3p3SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==

firstSuperUser:
  Email: root@gmail.com
  Name: root
  Password: root_password

logger:
  Encoding: console
  Level: debug

postgres:
  Host: db
  Port: 5432
  User: postgres
  Password: postgres
  Dbname: db

redis:
  Addr: redis:6379
  Password:
  Db: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240

taskRedis:
  Addr: redis:6379
  Db: 1

email:
  From: admin@admin.com
  Name: Go boilerplate
  Link: https://go-boilerplate.com
  LogoLink: https://media.vov.vn/sites/default/files/styles/front_large/public/2022-12/nhung-dieu-thu-vi-ve-logo-apple-ma-ban-chua-biet-4.png
  Copyright: Copyright © 2017 example inc. All rights reserved.
  VerificationSubject: Your account verification code
  ResetSubject: Your account password reset token

smtpEmail:
  Host: sandbox.smtp.mailtrap.io
  Port: 2525
  User: 1fa73a84091130
  Password: 9a817b2133d80c
  UseTls: true
  UseSsl: false
